name: gerar prainha pokemon
on:
  schedule:
    - cron: '0 0 * * *' # Atualiza automaticamente todo dia à meia-noite
  workflow_dispatch: # Permite que você force a atualização manualmente
  push:
    branches:
      - main
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: gerar a arte do grafico dos pokemon
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman' # Usamos a base arcade para injetar os sprites
      - name: salvar o cenario no seu repositorio
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
